templateproj/basicapp/urls.py
from django.urls import path
from basicapp import views

#Template Tagging
app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
    path('',views.index,name='index'),
]

templateproj/templateproj/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls'))
]

templateproj/basicapp/models.py
from django.db import models

# Create your models here.

templateproj/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':"Hello World",'number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

templateproj/templateproj/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

templateproj/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% block head_block %}
    <title>Base</title>
    {% endblock %}

    <!-- Link to bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:relative' %}">RELATIVE</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- anything outside will be inherited -->
      {% endblock %}
    </div>
  </body>
</html>

templateproj/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block head_block %}
    {% load my_extras %}
    <title>Home</title>
  {% endblock %}
  {% block body_block %}
    <h1>WELCOME TO INDEX PAGE</h1>
    <h2>This is <em>Index.html</em> showing</h2>
    <h1>{{ text|butt:'Hello' }}</h1>
    <h2>{{ number|add:"99" }}</h2>
  {% endblock %}

templateproj/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block head_block %}
  <title>Other</title>
  {% endblock %}
  {% block body_block %}

    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of Template Inheritance</h2>
  {% endblock %}

templateproj/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block head_block %}
  {% endblock %}
  <title>Relative</title>

    {% block body_block %}
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a class="btn btn-primary btn-lg" href="{% url 'basicapp:other' %}">Other</a>
    <a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}">Admin</a>
    <a class="btn btn-primary btn-lg" href="{% url 'basicapp:index' %}">Home</a>
    <a class="btn btn-primary btn-lg" href="{% url 'index' %}">Home</a>
    {% endblock %}